/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomainSuperAdminRouteImport } from './routes/_domain/super-admin'
import { Route as DomainAuthRouteImport } from './routes/_domain/auth'
import { Route as DomainSuperAdminUsersManagementRouteImport } from './routes/_domain/super-admin/users-management'
import { Route as DomainSuperAdminRolesPermissionsRouteImport } from './routes/_domain/super-admin/roles-permissions'
import { Route as DomainSuperAdminProfileRouteImport } from './routes/_domain/super-admin/profile'
import { Route as DomainSuperAdminCheckHealthRouteImport } from './routes/_domain/super-admin/check-health'
import { Route as DomainAuthResetPasswordRouteImport } from './routes/_domain/auth/reset-password'
import { Route as DomainAuthLoginRouteImport } from './routes/_domain/auth/login'
import { Route as DomainAuthForgetPasswordRouteImport } from './routes/_domain/auth/forget-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainSuperAdminRoute = DomainSuperAdminRouteImport.update({
  id: '/_domain/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainAuthRoute = DomainAuthRouteImport.update({
  id: '/_domain/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainSuperAdminUsersManagementRoute =
  DomainSuperAdminUsersManagementRouteImport.update({
    id: '/users-management',
    path: '/users-management',
    getParentRoute: () => DomainSuperAdminRoute,
  } as any)
const DomainSuperAdminRolesPermissionsRoute =
  DomainSuperAdminRolesPermissionsRouteImport.update({
    id: '/roles-permissions',
    path: '/roles-permissions',
    getParentRoute: () => DomainSuperAdminRoute,
  } as any)
const DomainSuperAdminProfileRoute = DomainSuperAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DomainSuperAdminRoute,
} as any)
const DomainSuperAdminCheckHealthRoute =
  DomainSuperAdminCheckHealthRouteImport.update({
    id: '/check-health',
    path: '/check-health',
    getParentRoute: () => DomainSuperAdminRoute,
  } as any)
const DomainAuthResetPasswordRoute = DomainAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => DomainAuthRoute,
} as any)
const DomainAuthLoginRoute = DomainAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DomainAuthRoute,
} as any)
const DomainAuthForgetPasswordRoute =
  DomainAuthForgetPasswordRouteImport.update({
    id: '/forget-password',
    path: '/forget-password',
    getParentRoute: () => DomainAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof DomainAuthRouteWithChildren
  '/super-admin': typeof DomainSuperAdminRouteWithChildren
  '/auth/forget-password': typeof DomainAuthForgetPasswordRoute
  '/auth/login': typeof DomainAuthLoginRoute
  '/auth/reset-password': typeof DomainAuthResetPasswordRoute
  '/super-admin/check-health': typeof DomainSuperAdminCheckHealthRoute
  '/super-admin/profile': typeof DomainSuperAdminProfileRoute
  '/super-admin/roles-permissions': typeof DomainSuperAdminRolesPermissionsRoute
  '/super-admin/users-management': typeof DomainSuperAdminUsersManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof DomainAuthRouteWithChildren
  '/super-admin': typeof DomainSuperAdminRouteWithChildren
  '/auth/forget-password': typeof DomainAuthForgetPasswordRoute
  '/auth/login': typeof DomainAuthLoginRoute
  '/auth/reset-password': typeof DomainAuthResetPasswordRoute
  '/super-admin/check-health': typeof DomainSuperAdminCheckHealthRoute
  '/super-admin/profile': typeof DomainSuperAdminProfileRoute
  '/super-admin/roles-permissions': typeof DomainSuperAdminRolesPermissionsRoute
  '/super-admin/users-management': typeof DomainSuperAdminUsersManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_domain/auth': typeof DomainAuthRouteWithChildren
  '/_domain/super-admin': typeof DomainSuperAdminRouteWithChildren
  '/_domain/auth/forget-password': typeof DomainAuthForgetPasswordRoute
  '/_domain/auth/login': typeof DomainAuthLoginRoute
  '/_domain/auth/reset-password': typeof DomainAuthResetPasswordRoute
  '/_domain/super-admin/check-health': typeof DomainSuperAdminCheckHealthRoute
  '/_domain/super-admin/profile': typeof DomainSuperAdminProfileRoute
  '/_domain/super-admin/roles-permissions': typeof DomainSuperAdminRolesPermissionsRoute
  '/_domain/super-admin/users-management': typeof DomainSuperAdminUsersManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/super-admin'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/super-admin/check-health'
    | '/super-admin/profile'
    | '/super-admin/roles-permissions'
    | '/super-admin/users-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/super-admin'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/super-admin/check-health'
    | '/super-admin/profile'
    | '/super-admin/roles-permissions'
    | '/super-admin/users-management'
  id:
    | '__root__'
    | '/'
    | '/_domain/auth'
    | '/_domain/super-admin'
    | '/_domain/auth/forget-password'
    | '/_domain/auth/login'
    | '/_domain/auth/reset-password'
    | '/_domain/super-admin/check-health'
    | '/_domain/super-admin/profile'
    | '/_domain/super-admin/roles-permissions'
    | '/_domain/super-admin/users-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainAuthRoute: typeof DomainAuthRouteWithChildren
  DomainSuperAdminRoute: typeof DomainSuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_domain/super-admin': {
      id: '/_domain/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof DomainSuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_domain/auth': {
      id: '/_domain/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof DomainAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_domain/super-admin/users-management': {
      id: '/_domain/super-admin/users-management'
      path: '/users-management'
      fullPath: '/super-admin/users-management'
      preLoaderRoute: typeof DomainSuperAdminUsersManagementRouteImport
      parentRoute: typeof DomainSuperAdminRoute
    }
    '/_domain/super-admin/roles-permissions': {
      id: '/_domain/super-admin/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/super-admin/roles-permissions'
      preLoaderRoute: typeof DomainSuperAdminRolesPermissionsRouteImport
      parentRoute: typeof DomainSuperAdminRoute
    }
    '/_domain/super-admin/profile': {
      id: '/_domain/super-admin/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof DomainSuperAdminProfileRouteImport
      parentRoute: typeof DomainSuperAdminRoute
    }
    '/_domain/super-admin/check-health': {
      id: '/_domain/super-admin/check-health'
      path: '/check-health'
      fullPath: '/super-admin/check-health'
      preLoaderRoute: typeof DomainSuperAdminCheckHealthRouteImport
      parentRoute: typeof DomainSuperAdminRoute
    }
    '/_domain/auth/reset-password': {
      id: '/_domain/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof DomainAuthResetPasswordRouteImport
      parentRoute: typeof DomainAuthRoute
    }
    '/_domain/auth/login': {
      id: '/_domain/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof DomainAuthLoginRouteImport
      parentRoute: typeof DomainAuthRoute
    }
    '/_domain/auth/forget-password': {
      id: '/_domain/auth/forget-password'
      path: '/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof DomainAuthForgetPasswordRouteImport
      parentRoute: typeof DomainAuthRoute
    }
  }
}

interface DomainAuthRouteChildren {
  DomainAuthForgetPasswordRoute: typeof DomainAuthForgetPasswordRoute
  DomainAuthLoginRoute: typeof DomainAuthLoginRoute
  DomainAuthResetPasswordRoute: typeof DomainAuthResetPasswordRoute
}

const DomainAuthRouteChildren: DomainAuthRouteChildren = {
  DomainAuthForgetPasswordRoute: DomainAuthForgetPasswordRoute,
  DomainAuthLoginRoute: DomainAuthLoginRoute,
  DomainAuthResetPasswordRoute: DomainAuthResetPasswordRoute,
}

const DomainAuthRouteWithChildren = DomainAuthRoute._addFileChildren(
  DomainAuthRouteChildren,
)

interface DomainSuperAdminRouteChildren {
  DomainSuperAdminCheckHealthRoute: typeof DomainSuperAdminCheckHealthRoute
  DomainSuperAdminProfileRoute: typeof DomainSuperAdminProfileRoute
  DomainSuperAdminRolesPermissionsRoute: typeof DomainSuperAdminRolesPermissionsRoute
  DomainSuperAdminUsersManagementRoute: typeof DomainSuperAdminUsersManagementRoute
}

const DomainSuperAdminRouteChildren: DomainSuperAdminRouteChildren = {
  DomainSuperAdminCheckHealthRoute: DomainSuperAdminCheckHealthRoute,
  DomainSuperAdminProfileRoute: DomainSuperAdminProfileRoute,
  DomainSuperAdminRolesPermissionsRoute: DomainSuperAdminRolesPermissionsRoute,
  DomainSuperAdminUsersManagementRoute: DomainSuperAdminUsersManagementRoute,
}

const DomainSuperAdminRouteWithChildren =
  DomainSuperAdminRoute._addFileChildren(DomainSuperAdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainAuthRoute: DomainAuthRouteWithChildren,
  DomainSuperAdminRoute: DomainSuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
